name: flutter_app
description: "A new Flutter project."
publish_to: 'none'  # Bu uygulama pub.dev'de yayınlanmayacak
version: 0.1.0      # Uygulama versiyonu

environment:
  sdk: ^3.5.4      # Flutter SDK versiyonu

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8       # iOS stil ikonlar için
  flutter_secure_storage: ^9.2.2 # Güvenli veri depolama için
  go_router: ^14.6.1            # Sayfa yönlendirme (routing) için
  shared_preferences: ^2.3.3     # Basit veri depolama için
  json_editor: ^0.0.8
  lottie: ^3.1.3
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0         # Kod kalitesi kontrolleri için

flutter:
  uses-material-design: true    # Material Design widget'larını kullanmak için
  assets:                       # Projedeki dosya kaynakları
    - lib/assets/images/           # Görseller için
    - lib/assets/icons/           # İkonlar için
    - lib/assets/languages/       # Dil dosyaları için
    - lib/assets/motions/        # Animasyon dosyaları için,
    
